#!/bin/bash
rootDir=$2
sudo ./container $1 $2 $3 ./test $1 $3
if [ -d $rootDir/sys/fs ]; then echo "FAILED: rmdir"; else echo "PASSED: rmdir"; fi
if mount | grep "$rootDir" >> /dev/null; then echo "FAILED: umount"; else echo "PASSED: umount"; fi

